### ISSUE TITLE
Move "High Contrast Particles" control into Visual tab of Preferences

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/build-an-atom#235] opened 2022-08-23 23:37 UTC
Its being moved from the OptionsDialog into Preferences for https://github.com/phetsims/joist/issues/837. This one seems best in the Visual tab of the dialog. This has been done and you can see the move on master. Assigning to responsible dev/designer from responsible_dev.md.

**Comment by jessegreenberg** [comment] 2022-08-24 12:20
Over slack @DianaTavares said she was unsure about this. @arouinfar can you confirm this is OK or assign to a responsible designer if necessary?

**Comment by zepumph** [comment] 2022-08-25 20:48
Given the way that the Preferences Dialog Design meeting went today, this does not belong in the "Visual" tab because it is not cross-sim, and so has more to do with the "content" of the simulation rather than the visuals. That said, I had a tenuous (at best) grasp on our decided direction, so I think that @arouinfar is the one to answer.

**Comment by jessegreenberg** [comment] 2022-08-25 21:00
That was not my interpretation and I didn't think we landed on "cross-sim" as the factor for deciding what should be in the "Simulation" tab. This control is purely for a visual representation and akin to "Projector Mode" so I think "Visual" is still best. But I am also fuzzy about it, it would be good to hear from @arouinfar.

**Comment by jbphet** [comment] 2022-08-29 23:42
For reference, here is the original issue that motivated the high-contrast-particles feature: https://github.com/phetsims/build-an-atom/issues/217.

**Comment by jbphet** [comment] 2022-08-29 23:53
The commits and the behavior seem reasonable.

Before closing this, we should make sure to notify the teacher who requested it.  Here is a reminder for that:

- [ ] IMPORTANT: Before closing this issue, let the teacher who originally requested this feature know that the change will appear someday.  @oliver-phet should have a record of who that person is, so please assign the issue to him when the work is complete and approved.

I think my part is done, so I'll unassign myself and let @arouinfar follow up on whether this is the appropriate design.

**Comment by arouinfar** [comment] 2023-09-08 22:07
I think it's appropriate to leave High Contrast Particles in the Visual tab of the Preferences dialog. Here are few reasons:
* It changes the visual appearance of the simulation and is not tied to any of the learning goals.
* The feature was designed to support learners with visual impairments. 
* When it comes to PhET-iO, Preferences associated with learner-specific modalities are not stateful to protect privacy. However, as a rule, all preferences under "Simulation" are stateful.
* There is precedent for sim-specific content being housed under tabs other than "Simulation". Here are examples from Quadrilateral and Number Compare:
  <img width="500" alt="image" src="https://github.com/phetsims/build-an-atom/assets/8419308/4ecedb44-0ded-4d8a-84c2-70184dc0da7b">
  <img width="500" alt="image" src="https://github.com/phetsims/build-an-atom/assets/8419308/55bdd10e-80c2-4fa0-b57b-e265bed99e6e">

@jbphet said:
> Before closing this, we should make sure to notify the teacher who requested it. Here is a reminder for that:

No need, the teacher was notified already in https://github.com/phetsims/build-an-atom/issues/217#issuecomment-763952117. This issue dealt with the migration from Options > Preferences and where to locate the "High Contrast Particles" control. However, the feature already appears in the published sim. Closing.

**Closed by arouinfar** 2023-09-08 22:07 UTC
Labels: status:ready-for-review
