### ISSUE TITLE
Third Game directs to second

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/build-an-atom#187] opened 2018-06-27 21:53 UTC
Test device: PC Laptop

Operating System: Windows 10 v. 1803

Browser: Chrome v. 67.0.3396.99

Problem description: When clicking on the third game on the game screen the user is redirected to the second game rather than the third game. 

Steps to reproduce: Open the sim, navigate to game screen, and start the third game from the left, it will open the second game and not the third. As you can see in the gif below the second and third game buttons both direct to the second game.

Screenshots: 
![baa_wrong_game](https://user-images.githubusercontent.com/30352536/42001558-9461e6b6-7a21-11e8-8c0d-9b1b56c2ff43.gif)

**Comment by jessegreenberg** [comment] 2018-06-28 14:48
@JRomero0613 I actually think that  @jbphet is the responsible dev for this sim. But if there was another reason I was assigned this issue please let me know.

**Comment by jbphet** [comment] 2018-06-29 20:16
Nice catch @JRomero0613.  This was caused by a cut-and-paste error introduced in https://github.com/phetsims/build-an-atom/commit/cc95a35b78260e6c3373a9db4c25ef8b31888dcb.  I've fixed it, and also cleaned up the code to reduce duplication, which should help prevent something like this from happening again.  Closing.

**Closed by jbphet** 2018-06-29 20:16 UTC
Labels: type:bug
