### ISSUE TITLE
Particle Bin is black.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/build-an-atom#78] opened 2013-11-19 20:15 UTC
Test device: Mac Book Pro
Operating System: 10.6.8
Browser: Safari 5.1.7
Problem description:
Particle pin is black when you initially open sim screens: "Atom" and "Symbol". If you select to "Atom" from "Symbol" or vice versa the issue of black particle bins is no longer present. 

Steps to reproduce:
Open sim
Select either "Atom" or "Symbol"
Severity:

Screenshots:

![screen shot 2013-11-19 at 1 00 35 pm](https://f.cloud.github.com/assets/5631059/1576083/50cdb6b6-5157-11e3-8a85-e2445d013a35.png)

Troubleshooting information (do not edit):
Name: Build an Atom
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.1.2-rc.2/build-an-atom_en.html
Version: 1.1.2-rc.2
Features missing: flexbox, touch, raf, svgfilters
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.57.2 (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2
Language: en-us
Window: 1024x599
Pixel Ratio: 1/1
WebGL: disabled

**Comment by jbphet** [comment] 2016-02-09 23:20
Unable to reproduce, probably fixed a while back.  Closing.

**Closed by jbphet** 2016-02-09 23:20 UTC
